.gitattributes
the `tests` folder should be excluded from export (fixing typo, currently it is `Tests`, with uppercase `T`)
=> Ignore `tests` from Git export

templates/embeds/card.html.twig
Add blocks `before` & `after` on `header/footer` (embeds/card) to allow devs to reproduce custom cards,
like `user card` on Tabler.io: https://preview.tabler.io/users.html
=> Add `before`/`after` on card blocks `header`/`footer`

templates/embeds/card.html.twig
BugFix when using `_fullsize`.
Class `p-0` was attached to the previous class.
Same fix for `collapse` to be more safe.
=> Card Embed - BugFix when using `_fullsize` and class name

templates/embeds/card.html.twig
Add the possibility to also collapse the footer on card embed.
- New `embed` param: `footer_collapsible`
- Add private variable `_collapsible_class` to be more clear
- Change use of `_id` only for the body id
- Change `button.action_collapsebutton` target on class name instead of id
```twig
{% embed '@Tabler/embeds/card.html.twig' with {collapsible : true, footer_collapsible : true} %}
[...]
{% endembed %}
```
=> [Feature] Embed card - Allow footer to be collapsed

templates/includes/menu.html.twig
Add the possibility to add `icon` on a `child item` from the menu.
Vertical:
Horizontal:
|  | Before | After |
|:---:|:---|:---|
| Comment | Items was align even if there's no icon | If no icon configured on item, the "block" is no longer present, so the label item will be put more on the left side.  |
| Result | ![image](https://user-images.githubusercontent.com/25293190/145591790-ce0dd449-8b97-4ceb-9f4f-77bf5dc84fed.png) | ![image](https://user-images.githubusercontent.com/25293190/145591979-df5b761f-e6eb-4c69-b415-2c035b589e18.png) |
=> Feature - Icons on child items menu

src/DependencyInjection/Configuration.php, templates/security.html.twig, tests/DependencyInjection/ConfigurationTest.php
Remove OLD AdminLTE comparison that breaks the render when default values 
used from `tabler.yaml` to disable "register link" for example.
FIX : 
- Registration ✔️ 
- Reset password ✔️
=> BugFix - login page render when default values from tabler.yaml

templates/security.html.twig
Add `tabindex` on login form inputs
=> Add `tabindex` on login form inputs

templates/components/button.html.twig, templates/components/buttons.html.twig
According to https://github.com/kevinpapst/TablerBundle/issues/27
Add macro to create real button submit from button macro.
Example:
```twig
{{ submit_button("save", {
title : 'action.save'|trans,
attr: {
'data-text' : 'test',
'data-loading-text' : 'action.saving'|trans ~ '...',
}
}, 'success') }}
```
HTML result:
```html
<button class="btn btn-success" type="submit" data-text="test" data-loading-text="action.saving...">
<i class="icon fas fa-save"></i>
Enregistrer
</button>
```
=> [Feature] Add TWIG submit_button() macro

templates/layout.html.twig
According to #19 & #21
Renaming blocks for breadcrumb.
From:
To:
---------------
From:
To:
=> [BugFix] Reorder blocks to match breadcrumb from Tabler.io doc

config/packages/tabler.yaml, docs/error_pages.md, docs/index.md, docs/layout.md, templates/error.html.twig, templates/extends/layout_fullpage.html.twig, templates/fullpage.html.twig, translations/TablerBundle.de.xliff, translations/TablerBundle.en.xliff, translations/TablerBundle.fr.xliff
Add `error` layout page.
404: `/_error/404.html`
500: `/_error/500.html`
=> [Feature] Add error layout + layout fullpage

templates/components/flash.html.twig
Update flash template. There were not displayed correctly.
https://preview.tabler.io/docs/alerts.html#dismissible-alerts
Before (not visible):
After:
=> [BugFix] Update flash to Tabler template

templates/components/button.html.twig
Fix a bug when tooltip is displayed with HTML title in the same time without icon
Hover on black button:
Hover on green button:
Hover on black button:
Hover on green button:
Hover on middle button:
=> BugFix tooltip when title displayed in raw HTML

src/Twig/RuntimeExtension.php, templates/components/alert.html.twig, templates/components/button.html.twig, templates/components/buttons.html.twig, templates/error.html.twig, templates/includes/menu.html.twig, templates/security/password-reset.html.twig
Attention: This can a BC break if you used more than an argument in the `|icon` filter or more than one argument in the `tabler_icon()` function before.
Fixes #68
=> change argument order to simplify icon usage outside buttons

templates/layout.html.twig
In case of the footer that is not on the bottom of the page, 
the only diff I've found with the demo is that class: https://preview.tabler.io/empty.html
Maybe BC Break ? not on my side.
Note: in the `fullpage.html.twig`, we have already changed that class.
With `.wrapper`:
With `.page`:
=> Change .wrapper to .page

templates/components/status_indicator.html.twig
See https://preview.tabler.io/docs/statuses.html#status-indicator
```twig
{% from '@Tabler/components/status_indicator.html.twig' import status_indicator %}
<div class="row align-items-center text-start">
<div class="col p-0">
{{ status_indicator({color : item.open ? 'green' : 'red', animated : false, extraClass :'float-end' }) }}
</div>
<div class="col p-0">
{{ item.open ? 'label.opened'|trans : 'label.closed'|trans }}
</div>
</div>
```
=> Add `status indicator` component

templates/components/alert.html.twig
Related to #89 
```twig
{% from '@Tabler/components/alert.html.twig' import alert %}
<div class="row">
<div class="col-6">
{{ alert('danger', 'Description' ,'Title', 'fas fa-exclamation-triangle', true) }}
{{ alert('danger', 'Description' ,'Title', 'fas fa-exclamation-triangle') }}
{{ alert('danger', 'Description' ,'Title', 'fas fa-exclamation-triangle') }} {# Error here #}
{{ alert('warning', 'Description' ,'Title') }}
{{ alert('warning', null ,'Title') }}
{{ alert('warning', null ,'Title', 'fas fa-exclamation-triangle') }}
{{ alert('success', 'Description') }}
{{ alert('success', 'Description', null, 'fas fa-exclamation-triangle') }}
{{ alert('primary') }}
</div>
<div class="col-6">
{{ alert({title : 'Title V2', description: 'Description V2', icon : 'warning', dismissible : true}) }}
{{ …
```
=> Refactoring `alert()` macro

templates/components/alert.html.twig
Fix of https://github.com/kevinpapst/TablerBundle/pull/90
=> BugFix Alert text style without `alert-important`

docs/embeds-offcanvas.md, templates/embeds/modal.html.twig, templates/embeds/offcanvas.html.twig, translations/TablerBundle.de.xliff, translations/TablerBundle.en.xliff, translations/TablerBundle.fr.xliff
Add offcanvas embed.
See: https://preview.tabler.io/offcanvas.html
```twig
{% embed '@Tabler/embeds/offcanvas.html.twig' with {position : 'top'} %}
{% block offcanvas_title 'Top offcanvas' %}
{% block offcanvas_body %}
<div>
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab assumenda ea est, eum exercitationem
illum itaque laboriosam magni necessitatibus, nemo nisi numquam quae reiciendis repellat sit soluta.
Aut!
</div>
{% endblock %}
{% endembed %}
{% embed '@Tabler/embeds/offcanvas.html.twig' with {position : 'end', hidden : false} %}
{% block offcanvas_title 'End offcanvas' %}
{% endembed %}
{% embed '@Tabler/embeds/offcanvas.html.twig' with {position : 'bottom'} %}
{% block offcanvas_title 'Bottom offcanvas' %}
{% endembed %}
{% embed '@Tabler/embeds/offcanvas.html.twig' …
```
=> Add offcanvas embed

src/Model/UserInterface.php, templates/security.html.twig, templates/security/confirmation.html.twig, templates/security/password-reset.html.twig, templates/security/registration.html.twig
Some random cleanup commits with tiny BC break if someone relied on the `fos_user_registration_register` class or used the `fos_user_content` block (which I hope nobody did).
My main purpose was to get rid of the last `fos_user` references from the AdminLTE era - fixes #33
=> Cleanup FOS user references

templates/includes/menu.html.twig
- [] New feature (non-breaking change which adds functionality)
=> Fix 'active' display on menu

docs/components-status-dot.md, docs/components-status.md, docs/index.md, templates/components/status.html.twig, templates/components/status_dot.html.twig
Added `status()` and `status_dot` macros
=> New status() and status_dot() macros

docs/components-buttons.md, templates/components/buttons.html.twig
This change allows `actions` of `dropdown_button` to have customized `attr` like any other button. This change allows to trigger modals etc. from within a dropdown.
=> Allow custom attr in dropdown buttons

templates/includes/menu.html.twig, templates/includes/navbar_user.html.twig
=> handle null URL in navigation/menu models

docs/form_theme.md
=> BugFix themes link

templates/layout-horizontal.html.twig, templates/layout-vertical.html.twig
If we add class in the Twig block "body_class", the text is put AFTER the value of the class attribute.
Ex: 
`{% block body_class %}layout-boxed{% endblock %}`
Result:
`<body class="antialiased" layout-boxed>`
=> Move Twig block "body_class" into the class attribute of BODY

templates/includes/html_head.html.twig, templates/layout-horizontal.html.twig, templates/layout-vertical.html.twig, templates/security.html.twig
- extract html head default tags to include (allows to override via new file in app `templates/bundles/TablerBundle/`templates/includes/html_head.html.twig`)
- add `rel=noindex.nofollow` to prevnt public apps from showing up in search engines
=> include for html_head and rel=nofollow

docs/embeds-card-vertical-navigation.md, src/Twig/RuntimeExtension.php, src/Twig/TablerExtension.php, templates/embeds/card-vertical-navigation.thml.twig, templates/includes/utils.html.twig, tests/Twig/TablerExtensionTest.php
As discussed in https://github.com/kevinpapst/TablerBundle/discussions/116
TODO 📋 
All content tab must be rendered
```twig
{% set items = [
{
name: 'Account',
content: '<h1>My Account</h1><h3>Profile Details</h3>'
},
{
name: 'Notifications',
content: include('notifications.html.twig')
},
{
name: 'Experience',
header: true
},
{
name: 'Feedback',
content: '<h1>Give Feedback</h1>'
},
{
name: 'Automates',
header: true
},
{
id: 'auto',
name: tabler_icon('robot') ~ " " ~ 'label.variable.automated.plural'|trans|capitalize,
raw: true,
content : _self.automate_content(mentions, automated_values)
}
] %}
{% embed '@Tabler/embeds/card-vertical-navigation.thml.twig' with {items : items} %}{% endembed %}
```
Only one tab content is completed, rest is only for navigation between urls
```twig
{% set …
```
=> Add card Bootstrap tabs navigation

templates/embeds/card.html.twig
Here we go... I finally did it by need.
I was tired of not having auto-completion from Symfony PhpStorm plugin
and searching 30 minutes every-time what I need to change on that embed..
There are NO deleted options/variables/blocks.
Only new ones.
So it should not BC.
It allows dev to "unset" block by setting them at an empty string.
That means:
<table>
<tr>
<td>
```twig
{% block box_footer %}{% endblock %}
```
</td>
</tr>
<tr>
<td>
```twig
{% block box_footer -%}
{%- endblock %}
```
</td>
</tr>
</table>
<table>
<tr>
<td>
```twig
{% block box_footer %} {% endblock %}
```
</td>
</tr>
<tr>
<td>
```twig
{% block box_footer %}
{% endblock %}
```
</td>
</tr>
</table>
```twig
{% embed '@Tabler/embeds/card.html.twig' %}
{% block box_title %}Title{% endblock %}
{% endembed %}
{% embed …
```
=> [Card] Refactoring V1

docs/layout.md, src/DependencyInjection/Configuration.php, src/Helper/ContextHelper.php, templates/security-cover.html.twig, templates/security.html.twig, templates/security/login-cover.html.twig, tests/DependencyInjection/ConfigurationTest.php, tests/Helper/ContextHelperTest.php
Add login cover page from Tabler : https://preview.tabler.io/sign-in-cover.html
<del>
⚠️ Many parts of the code is copy-pasta from `security.html.twig`.
The only "new" code is before the login form AND after.
As a twig "way to work", devs cannot override blocks inside of an embed/include..
How do you want to handle that duplicated code @kevinpapst?
</del>
Extended from `/security.html.twig`
=> [Login] Add Login-cover page

src/Model/MenuItemInterface.php, src/Model/MenuItemModel.php, templates/includes/menu.html.twig
added method to configure translation domain
BC break: adds a new method to the `MenuItemInterface`.
If you are not using the built-in MenuItemModel, you have to update your code!
=> added method to configure translation domain

templates/embeds/card.html.twig
A Card with a fullsized table from Tabler should apparently not be inside `card-body`.
See here for Tabler demo: https://preview.tabler.io/tables.html (see `invoices` table)
With empty body and no padding (`fullsize` card template option) + Table inside card-body
I've added condition to not always print this part.
=> [Card] Add `.card-body` print condition

templates/components/accordion.html.twig
Allows an accordion item to be more customizable
=> [Accordion] Add bodyClasses & before & after

templates/embeds/collapsible.html.twig
=> added combined card-accordion component

templates/components/alert.html.twig
=> [Alert] Add `id` and `attr` option

templates/layout-vertical.html.twig
This fixes code/logic that is not in Tabler today. 
See `<header>` at https://preview.tabler.io/layout-combo.html
It ends up as a bug when you want to redefine the primary color:
As it is today:
-------
How it should be (as Tabler demo):
Works as expected in mobile view:
=> [Vertical layout] Remove `data-bs-theme` from header

templates/components/status.html.twig, templates/components/status_dot.html.twig, templates/components/status_indicator.html.twig
- Deprecate non camelCase `with_dot` option
- Add safe `bool` check on options values
- ~Add `status_dot` component~
- add `attr` option to each component
```twig
<div>
{{ status('Not animated', {withDot : true, animated : false, color: 'blue'}) }}
{{ status('Lite with dot', {withDot : true, color: 'red', lite: true}) }}
{{ status('No dot', {color: 'green'}) }}
{{ status('id', {attr: {id : 'status_id'}}) }}
{{ status_dot() }}
{{ status_dot({color : 'purple'}) }}
{{ status_dot({color : 'red', animated : false}) }}
{{ status_dot({attr: {id : 'status_dot_id'}}) }}
{{ status_indicator() }}
{{ status_indicator({color : 'orange'}) }}
{{ status_indicator({color : 'red', animated : false}) }}
{{ status_indicator({attr: {id : 'status_indicator_id'}}) }}
</div>
```
=> [Status] Add `attr` option + deprecated non camelCase option

.editorconfig, templates/security.html.twig, translations/TablerBundle.de.xlf, translations/TablerBundle.en.xlf, translations/TablerBundle.fr.xlf
=> [Login] Show password in login/sign up form

templates/components/dropdown.html.twig
Fix the deprecation `Deprecated: Since twig/twig 3.15: Add explicit parentheses around the "??" binary operator to avoid behavior change in the next major version as its precedence will change in "@Tabler/components/dropdown.html.twig" at line 29. `
=> Fix Twig 3.15 deprecation on ?? usage

src/DependencyInjection/TablerExtension.php
This solves the deprecation reported when running with Symfony v7.2:
> The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "KevinPapst\TablerBundle\DependencyInjection\TablerExtension".
See as an example: https://github.com/hwi/HWIOAuthBundle/pull/2005
=> Use non-deprecated Extension class

templates/layout-horizontal.html.twig, templates/layout-vertical.html.twig
In case we want to replicate the [Tabler map-fullsize](https://preview.tabler.io/map-fullsize.html),  
we need to override the entire `page-body` and add a class to the `page-wrapper`
This can now be done as follows:
```twig
{% extends '@Tabler/layout-vertical.html.twig' %}
{% block page_wrapper_class %}page-wrapper-full{% endblock %}
{% block page_header %}{% endblock %}
{% block page_body %}
<div class="page-body">
<div
class="map flex-fill"
></div>
</div>
{% endblock %}
{% block footer %}{% endblock %}
```
| Vertical| Horizontal|
|--------|--------|
| ![vert](https://github.com/user-attachments/assets/6a65542c-db30-42f4-bd61-77b49bcae797)| ![horz](https://github.com/user-attachments/assets/6c1860de-2db8-4d6f-b5cc-707cf6eeb8cf)|
=> Add more layout flexibility
