templates/security.html.twig
From https://github.com/kevinpapst/TablerBundle/issues/8
Update twig condition on `csrf_token` of login form template
=> Update twig condition on `csrf_token`

.github/workflows/linting.yaml, src/Event/MenuEvent.php, templates/includes/menu.html.twig
=> support badges in menu

templates/layout.html.twig
=> [Templating] Added block page_header to default layout

templates/embeds/modal.html.twig
Add start blocks to modal to allow devs to customize even more the embeded.
My Modal raw HTML to translate:
```html
<div
class="modal fade"
tabindex="-1"
aria-hidden="true"
data-modal-form-target="modal" // !!!!!!!!!!!!!!! need that
>
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h5 class="modal-title">{{ modalTitle }}</h5>
<button type="button" class="btn-close"
data-bs-dismiss="modal"
aria-label="Close"></button>
</div>
<div
class="modal-body"
data-modal-form-target="modalBody"  // !!!!!!!!!!!!!!! need that
data-action="submit->modal-form#submitForm" // !!!!!!!!!!!!!!! need that
>
{{ modalContent|default('Loading...') }}
</div>
<div class="modal-footer">
<button type="button" class="btn btn-secondary"
data-bs-dismiss="modal">Cancel
</button>
<button …
```
=> [Feature] Add modal `start` blocks

docs/index.md, docs/layout.md, docs/twig-context.md, templates/embeds/card.html.twig, templates/error.html.twig
- Fixes #49 
- Fix homepage link in error template 
- Added variable to customize card bottom margin
=> Fixes (best PR name in the world!)

docs/index.md, docs/theme/override_theme.md, docs/theme/theme.scss
Add theme override example/doc
=> Add theme override example/doc

docs/components-timeline.md, docs/index.md, templates/components/timeline.html.twig
Add the tabler Timeline component into macro.
https://preview.tabler.io/docs/timelines.html
```twig
{% from '@Tabler/components/timeline.html.twig' import timeline %}
{{ timeline([
{ icon: 'user',     iconColor: 'warning',   time: '10 hours ago',   title: 'Users',         text:'User was created' },
{ icon: 'delete',   iconColor: 'danger',    time: '12 hours ago',   title: 'Item deleted',  text:'An item has been deleted.' },
{ icon: 'plus',     iconColor: 'success',   time: '1 day ago',      title: 'Item created',  text:'Element has been created.' },
{ icon: 'plus', time: '1 day ago', title: 'Item created'},
{ icon: 'plus', time: '1 day ago'},
{ icon: 'plus'},
{ icon: 'plus', time: '2 days ago', title: 'Item created', text: 'Element has been created.' },
{ time: '2 days ago', title: 'Item …
```
=> Add timeline Tabler component

templates/embeds/card.html.twig
Add class header option.
Allow us to add bg to the header for example.
```twig
{% embed '@Tabler/embeds/card.html.twig' with {fullsize: true } %}
{% block box_class %}border border-warning{% endblock %}
{% block box_header_class %}bg-warning{% endblock %}
{% block box_title %}
{{ tabler_icon('error') }} {{ 'title.element.unknown.plural'|trans }}
{% endblock %}
{% block box_body %}
{% endblock %}
{% endembed %}
{% embed '@Tabler/embeds/card.html.twig' with {fullsize: true } %}
{% block box_class %}border border-success{% endblock %}
{% block box_header_class %}bg-success{% endblock %}
{% block box_title %}
{{ tabler_icon('success') }} {{ 'title.element.known.plural'|trans }}
{% endblock %}
{% block box_body %}
{% endblock %}
{% endembed %}
```
Result:
=> Add header class

templates/embeds/card.html.twig
This change allows to change the status position to "top", "start" & "bottom"
A clear and concise description of what this pull request adds or changes.
=> Add status_position to card embed

templates/fullpage.html.twig, templates/layout.html.twig
=> Add block body_class to templates

docs/components-timeline.md
Add doc example, because I've forgot what does what.
So more doc is welcome 😉
=> Add preview screenshot

templates/components/steps.html.twig
See https://preview.tabler.io/docs/steps.html
```twig
{% from '@Tabler/components/steps.html.twig' import steps %}
{{ steps([
{title : 'Step 1', clickable : false},
{title : 'Step 2'},
{title : 'Step 3', active : true},
{title : 'Step 4', description : 'More detailed description'},
{title : 'Step 5', href: 'https://www.google.com', clickable : true},
],{
tooltip : true,
color: 'red',
counter : true,
}) }}
```
=> Add steps component

docs/components-status-indicator.md
=> [doc] Add `Status indicator` component doc

templates/components/button.html.twig, templates/components/steps.html.twig, templates/includes/utils.html.twig
Related to https://github.com/kevinpapst/TablerBundle/issues/85
=> [Macros] Add `attr to html` twig macro for components

docs/components-steps.md
=> [doc] Add Steps component doc

docs/components-callout.md, docs/index.md, templates/components/callout.html.twig
Needed changes after https://github.com/kevinpapst/TablerBundle/pull/90
=> Fix callout embed

templates/embeds/modal.html.twig
=> Add more modal class blocks

docs/theme.scss
Add more detailed DOC about theme override
=> Update theme override doc

docs/theme.scss
Update doc due to Tabler version update 15
=> Update DOC theme with last Tabler version

src/Model/MenuItemInterface.php, src/Model/MenuItemModel.php, templates/includes/menu.html.twig
Contains a BC break, as there is one more method in the MenuItemInterface
=> allow to manually expand menus in vertical navigation

templates/components/timeline.html.twig
=> Added null check to timeline item parts

docs/embeds-card-nav.md, templates/embeds/card_nav.html.twig, templates/embeds/card_nav_header.html.twig
```twig
{% set raw_html_example %}
<div class="card-body">
<h3><span class="badge bg-success">Active</span> content</h3>
<p class="mb-0">With some text</p>
</div>
<div class="card-footer">
<div class="d-flex">
<a href="#" class="btn btn-link">Cancel</a>
<a href="#" class="btn btn-primary ms-auto">Go somewhere</a>
</div>
</div>
{% endset %}
{% set items = [
{
name : 'First',
content : 'First content',
},
{
name : '<i class="fas fa-times me-2"></i>Disabled',
content : 'Disabled content',
disabled : true,
raw : true,
},
{
name : 'Active',
content : raw_html_example,
active : true,
raw : true,
},
{
name : 'Url',
url : 'https://www.w3schools.com/',
},
] %}
{% embed '@Tabler/embeds/card_nav.html.twig' with { items : items} %}{% endembed %}
{% embed '@Tabler/embeds/card_nav.html.twig' with { …
```
=> [Card] Add Card component with nav

.github/release-drafter.yml, .github/workflows/release-drafter.yaml
To minimize manual work for new releases
=> added release drafter

templates/layout-horizontal.html.twig, templates/layout-vertical.html.twig
Update action layout as current tabler version: https://preview.tabler.io/layout-combo.html.
From:
To:
=> [Layout] Update title actions default responsive

docs/components-accordion.md, templates/components/accordion.html.twig
Add `attr` option to accordion component
=> Add `attr` on accordion & item
